---
-  hosts: master
   tasks:
   - name: copy jar/war onto tomcat servers
     copy:
       src: /var/lib/jenkins/workspace/ansible/jenkins-docker-ansible-project/target/java-tomcat-maven-example.war
       dest: /usr/share/tomcat/webapps/
