---
-  hosts: master
   tasks:
   - name: copy jar/war onto tomcat servers
     copy:
       src: /var/lib/jenkins/workspace/jenkins-ansible-maven/target/java-tomcat-maven-example.war
       dest: /usr/share/tomcat/webapps/
